version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
